Tutorial model changes
matthias-k/pysaliency pull request #87
Opened 2024-10-28 15:28 UTC by JanRiedelsheimer

2024-10-28 19:26 UTC, matthias-k requested changes

2024-10-28 19:26 UTC, matthias-k commented on notebooks/Tutorial.ipynb
Because the notebook is too large, I don't manage to annotate individual changes, so I'll write a summary comment here. Sorry if it looks a bit unorganized, I did my best...
- please run the whole notebook at the end once in a full go. This makes sure that everything works and that the cell numbers are consecutive. It always looks a bit strange, if they are all over the place, and also it should make the git diff much more concise :).
- import cell: You adapted the import path (see below), please add a comment that this is needed when running the notebook from within the pysaliency repository without having pysaliency installed. If people just copy and paste the code to try it in their installation, this is not needed.
```
import sys
sys.path.insert(0, '..')
```
- import cell, you changed the matlab path. Please add a comment that this is necessary if matlab is not in the default path, maybe leave both the linux and mac version commented out and mark them as examples, something like
```
# if matlab is not in the global path, you have to include it in the PATH variable. The specific location will depend on your setup, e.g.:
# os.environ['PATH'] = f"/usr/local/MATLAB/R2024a/bin/:{os.environ['PATH']}"
# os.environ['PATH'] = f"/Applications/MATLAB_R2024b.app//bin/:{os.environ['PATH']}"
```
- please remove the cell with the TODOs
- in the spatial saliency model's _log_density, you removed this comment, please readd it.
```
        # _log_density can either take pysaliency Stimulus objects, or, for convenience, simply numpy arrays
        # `as_stimulus` ensures that we have a Stimulus object
```
- same cell, please use a more clear name than `ksize`, I would suggest `kernel_size`. I now that short names are not uncommon, but I really came to appreciate verbose variable names for readability. I'm happy to tell you more about this opinion :).
```
        # define kernel size based on image size
        ksize = np.round(self.width * max(width, height)).astype(int)
```
- same cell, the second Gaussian takes as input the squared difference, not the difference itself. This will also remove the problem with negative values
```
prediction = gaussian_filter(gray_stimulus - blurred_stimulus, sigma)
```
- you removed the cell with this comment, was there a specific reason? Otherwise please readd it. It also screws up the following diff in VSCode a lot :D.
```
When using the model, we use the function `log_density`, which mainly adds a cache around `_log_density` to avoid recomputing log densities multiple times. This is how the resulting prediction looks like:
```
- if I'm not mistaken, there still is the cell with the `MySimpleModel`, that one should be removed, right?
- let's also change the comparison with DeepGaze vs the simple model to DeepGaze vs the new contrast model
- `MySimpleScanpathModel`: Let's rename the `prior_width` keyword argument to something more appropriate. Maybe `spatial_model_bandwidth`. And now that I think about, we should also rename the parameter in the LocalContrastModel from `width` to `bandwidth`, since it's not a central Gaussian anymore.
- Great idea to add the prior to the figure for the scanpath model, thanks!
- There is a cell with an exception because of a missing pandas dependency. That should not be in the commited notebook ;).

2024-10-28 19:26 UTC, matthias-k commented on .DS_Store
Can you please remove this file from the PR? It should not be commited. Feel free to add it to the `.gitignore` instead. I never needed to, because I'm not using mac.

2024-10-29 10:33 UTC, JanRiedelsheimer commented on notebooks/Tutorial.ipynb
The Gaussian Model is still needed as center bias for DeepGaze right? 
`# deepgaze needs a spatial prior, for which we use our Gaussian model here
deepgaze1_model = pysaliency.external_models.DeepGazeI(centerbias_model=my_simple_model)`

2024-10-29 10:40 UTC, JanRiedelsheimer commented on notebooks/Tutorial.ipynb
Also at the end of the notebook the information gain is described, I think calculating the information gain over the center bias makes sense
`print("information gain relative to a uniform baseline model   ", deepgaze1_model.information_gain(stimuli, eval_fixations, average='image'))
print("information gain relative to a centerbias baseline model", deepgaze1_model.information_gain(stimuli, eval_fixations, baseline_model=my_simple_model, average='image'))`

2024-11-04 14:05 UTC, matthias-k commented
You added the `.DS_Store` to the gitignore, but the file is still included in this PR. You will need to, e.g. `git rm` it and commit the removal to get it out of the PR again.

2024-11-04 14:07 UTC, matthias-k commented on notebooks/Tutorial.ipynb
Regarding the information gain: technically yes, but it would be important to have a _good_ center bias model here. So I would prefer to keep it to the uniform baseline for now, and I'm happy to change it to a KDE model in a separate PR. But I fully agree that we should use information gain with a good baseline model in the tutorial.

2024-11-04 14:14 UTC, matthias-k commented on notebooks/Tutorial.ipynb
Thinking again about: let's keep in the centerbias for now, I can change it at some point if I feel sufficiently strong about it :)

2024-11-11 10:29 UTC, matthias-k commented
Thanks, looks good now!

2024-11-11 10:31 UTC, merged