http_server first commit
matthias-k/pysaliency pull request #90
Opened 2024-11-11 11:47 UTC by JanRiedelsheimer

2024-11-11 14:40 UTC, matthias-k requested changes
Thanks! I mentioned a few things that we discussed so that you see what exactly they apply to.

2024-11-11 14:40 UTC, matthias-k commented on http_submission/sample_evaluation.py
> +        payload = pickle.dumps(inputs)
We don't want to use pickle, because that's special to python. I think we discussed it last week:
- let's use a file attachement with an image file for the stimulus
- let's encode everything else as json data

2024-11-11 14:40 UTC, matthias-k commented on http_submission/sample_evaluation.py
> +class HTTPScanpathModel(pysaliency.ScanpathModel):
This model makes sense to have as a regular pysaliency model. I think there is a TODO for it, where I suggested something like `pysaliency.http_models`. Now that I think about it, maybe let's simply use `pysaliency.http`

2024-11-11 14:40 UTC, matthias-k commented on http_submission/sample_evaluation.py
> +    print(
for the example evaluation, let's use a proper image, e.g. `scipy.misc.face()`. Besides computing the conditional log density, let's also add a proper evaluation: you can build a stimulus object with just the `face` image, add some handbuild scanpaths (check the pysaliency tests for examples) and compute the information gain. This will test a bit more generally and also give users a better idea

2024-11-11 14:40 UTC, matthias-k commented on http_submission/sample_submission.py
> +class SampleScanpathModel():
Just for the sake of completeness, since we just discussed it: Let's make this an actual model, maybe the one from the tutorial.

2024-11-11 14:40 UTC, matthias-k commented on http_submission/model_server.py
> +    payload = request.get_data()
see the comment in the `HTTPScanpathModel` and my example snippet for how to transfer the data in a less python-specific way

2024-11-12 11:41 UTC, JanRiedelsheimer commented on http_submission/sample_evaluation.py
> +    print(
Isn't it more effective to use a real Stimulus from MIT1003?

2024-11-12 12:40 UTC, matthias-k commented on http_submission/sample_evaluation.py
> +    print(
It's actually much nicer, I just thought about avoiding forcing people to download MIT1003. But you're right, let's simply use MIT1003 for now

2024-11-13 13:54 UTC, matthias-k commented on http_submission/requirements.txt
> +cython
Is cython really required? I thought I sucessfully managed to make it an optional dependency, but maybe I missed something...

2024-11-19 10:56 UTC, matthias-k commented on http_submission/sample_evaluation.py
> +        self.log_density_url = url + "/conditional_log_density"
I would suggest to use properties for that. Right now, if you change the url (for whatever reason), the dependent urls are not updated

2024-11-19 10:59 UTC, matthias-k commented on http_submission/sample_evaluation.py
> +    def type(self):
the type mainly needs to be checked to make sure that the server is compatible with this model. So I would suggest to call the function something like `check_type`:
```
def check_type(self):
    response = requests...
    if not response['type'] == 'ScanpathModel':
        raise ...
    if not response['version'] in ['v1.0.0']:
        raise ...
```

Then you can call `check_type` in `__init__` to make sure that the server is valid.

2024-12-03 15:10 UTC, matthias-k commented on pysaliency/http_models.py
> +        # TODO in constuctor aufrufen, damit direkt gecheckt wird ob type passt
delete ;)

2024-12-03 15:17 UTC, merged